name: Deploy Order Service to EKS

on:
  push:
    paths:
      - 'order-service/**'
      - '.github/workflows/deploy-order.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/order-service:latest ./order-service
        docker push ${{ secrets.DOCKER_USERNAME }}/order-service:latest

    - name: Set up kubeconfig from secret
      run: |
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig.yaml

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to EKS
      env:
        KUBECONFIG: kubeconfig.yaml
      run: |
        kubectl apply -f k8s-manifests/order-deployment.yaml
