name: Deploy Game Service to EKS

on:
  push:
    paths:
      - 'game-service/**'
      - '.github/workflows/deploy-game.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/game-service:latest ./game-service
        docker push ${{ secrets.DOCKER_USERNAME }}/game-service:latest

    - name: Set up kubectl
      run: |
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s-manifests/game-deployment.yaml
